### ISSUE TITLE
Black page

### ISSUE THREAD

**Issue by vasfvitor** [Playform/AstroStarterTemplate#235]
Hi, the page linked is black https://astro-starter-template.pages.dev/
I've created a project from a template and it's also black. I've tested both on Firefox and the other browser. No errors on browser console or terminal.

Any idea as what is the cause?

![image](https://github.com/Playform/AstroStarterTemplate/assets/61759797/f706751a-cca4-4e49-a19d-9376a9d75ef4)

**Comment by NikolaRHristov** [comment]
This is expected, the page is just a blank template. It's currently because of the https://github.com/Playform/AstroStarterTemplate/blob/main/Source/Stylesheet/Global.css

`dark:bg-black`, which only applies a dark background on `@media (prefers-color-scheme: dark) {`

```css
body {
	@apply flex
		flex-grow
		flex-col
		antialiased
		dark:bg-black
		dark:text-white
		sm:subpixel-antialiased;
}
```
